### ISSUE TITLE
Docs for basic usage

### ISSUE THREAD

**Issue by shubhamkumar13** [facebook/ocamlrep#45]
Is it possible to have some simple basic examples which show a cargo project and a dune project working together

**Comment by Abinash018** [comment]
I think it is possible

**Comment by Abinash018** [comment]
May some way possible

**Comment by shayne-fletcher** [comment]
it is possible to get builds going with ocamlrep, dune & cargo. see [errpy](https://github.com/facebook/errpy) for example which utilizes ocamlrep. errpy is [available in opam](https://opam.ocaml.org/packages/errpy/) and is integrated into [pyre-check](https://github.com/facebook/pyre-check)

i would advocate for the use of [buck2](https://buck2.build/) though. one can use [reindeer](https://github.com/shayne-fletcher/reindeer) for the rust dependencies and [ocaml-scripts](https://github.com/shayne-fletcher/ocaml-scripts) for the opam dependencies. there are [some ocaml examples (including rust embedding)](https://github.com/facebook/buck2/tree/main/examples/with_prelude/ocaml) in the [buck2 repo](https://github.com/facebook/buck2) (sadly not involving ocamlrep though). ocamlrep itself [builds with buck2 and reindeer](https://github.com/facebook/ocamlrep/blob/main/README-BUCK.md) in addition to cargo.

**Comment by mheiber** [comment]
Hopefully https://github.com/facebook/ocamlrep/issues/45#issuecomment-1971799618 helps.
There hasn't been action here for a while, so closing.
Sorry there aren't more docs–I don't think this project is under active dev.
